#!/bin/sh
#
# Daemon application
#
case "$1" in
  start)
	modprobe fan_drv
  	/usr/local/fand
    echo "Daemon fand launched"
	;;
  stop)
  	killall fand
	;;
  restart|reload)
  	killall fand
	/usr/local/fand
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?